spring:
  main:
    allow-circular-references: true
logging:
  level:
    org:
      mipams:
        jumbf:
          core: INFO
          privsec: INFO
        fake_media: DEBUG
org:
  mipams:
    core:
      max_file_size_in_bytes: 52428800 # Maximum size per file uploaded: 50 MB
      image_folder: /home/nikos/Desktop/demo
